### ISSUE TITLE
Support for testing newly added github actions in code 

### ISSUE THREAD

**Issue by PuneetPunamiya** [cpanato/github-actions-dashboard#50]
Can this be used to test a new github action as well ?

Let's say if I'm adding a new github action in my repo and I want to test this before pushing it to the branch 

Can we use this application in that case

**Comment by cpanato** [comment]
no, this is to check the "health" state of your job, like if they run successfully, if failed or aborted, this only shows for existing jobs
it is more a dashboard to visually see the state of your jobs

i will close this issue, hope that helps
